apiVersion: v1
kind: Service
metadata:
  name: frontend-loadbalancer
  annotations:
    service.kubernetes.io/session-affinity: "ClientIP"
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    app: frontend
